import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'es' | 'en';

interface Translations {
  [key: string]: {
    [key: string]: string;
  };
}

const translations: Translations = {
  es: {
    'nav.triage': 'Triaje',
    'nav.pharmacy': 'Farmacias',
    'nav.search': 'Buscar',
    'nav.rewards': 'Premios',
    'nav.activity': 'Retos',
    'nav.history': 'Historial',
    'nav.appointments': 'Citas',
    'nav.membership': 'Membresía',
    'nav.dashboard': 'Panel',
    'header.emergency': 'Emergencia',
    'header.notifications': 'Notificaciones',
    'header.map': 'Mapa de Salud',
    'header.activity': 'Actividad y Retos',
    'profile.title': 'Mi Perfil de Salud',
    'profile.settings': 'Ajustes',
    'profile.logout': 'Cerrar Sesión',
    'profile.status.frequent': 'Paciente Frecuente',
    'profile.status.verified': 'Identidad Verificada',
    'profile.blood': 'Grupo Sanguíneo',
    'profile.allergies': 'Alergia Crítica',
    'profile.birth': 'Nacimiento',
    'profile.personal_info': 'Información Personal',
    'profile.validate': 'Validar Identidad',
    'profile.validate_desc': 'Se requiere validación biométrica o PIN para editar información sensible',
    'profile.phone': 'Teléfono',
    'profile.email': 'Correo Electrónico',
    'profile.address': 'Ubicación Residencial',
    'profile.save': 'Guardar Cambios',
    'profile.saving': 'Guardando...',
    'profile.docs': 'Documentación Médica',
    'profile.scan': 'Digitalizar Orden',
    'profile.sync_error': 'Problema al sincronizar',
    'profile.retry': 'Intentar de nuevo',
    'profile.sync_success': 'Documento sincronizado con éxito',
    'profile.upload_desc': 'Arrastra o selecciona tus archivos',
    'profile.upload_sub': '(Recetas, Informes, Laboratorio • Máx 10MB)',
    'profile.select_files': 'Seleccionar Archivos',
    'profile.recent_files': 'Archivos Recientes',
    'profile.emergency_contacts': 'Contactos de Emergencia',
    'profile.add_contact': 'Añadir Contacto',
    'profile.health_config': 'Configuración de Salud',
    'profile.sync_cloud': 'Sincronización en la nube',
    'profile.sync_vault': 'Respaldo seguro en Supabase Vault',
    'profile.local_storage': 'Almacenamiento Local (Modo Offline)',
    'profile.indexdb': 'Mantener caché vital en IndexedDB',
    'profile.preview': 'Vista Previa',
    'profile.confirm': 'Confirmar',
    'profile.cancel': 'Cancelar',
    'profile.change_photo': 'Cambiar Foto',
    'profile.passport': 'Pasaporte Digital Sanit',
    'profile.passport_desc': 'Usa este código para acceso rápido en clínicas y farmacias de la red.',
    'profile.generate_temp': 'Generar Acceso Temporal',
    'profile.temp_active': 'Acceso Dinámico Activo',
    'profile.expiry': 'Expira en',
    'profile.not_validated': 'Validar para añadir contactos',
    'profile.add_trusted': 'Añadir Contacto de Confianza',
    'profile.validated_true': 'Identidad validada correctamente',
    'profile.name_label': 'Nombre',
    'profile.rel_label': 'Parentesco',
    'profile.edit': 'Editar', //
    'profile.delete': 'Eliminar',
    'profile.encryption': 'Cifrado de Extremo a Extremo',
    'profile.encryption_desc': 'Requiere autenticación biométrica para desencriptar historial clínico y documentos locales.',
    'profile.encryption_status': 'Estado de Cifrado',
    'profile.system_active': 'SISTEMA ACTIVO',
    'profile.share_temp': 'Compartir acceso temporal',
    'profile.code_active': 'Código Activo',
    'profile.view_qr': 'Ver Mi QR',
    'profile.temp_expiry': 'El código temporal expira en 15 minutos',
    'profile.logout_full': 'Cerrar Sesión de Salud',
    'biometric.title': 'Validación Biométrica',
    'biometric.desc': 'Escanea tu huella o usa el reconocimiento facial para desbloquear la edición de datos sensibles.',
    'biometric.start': 'Iniciar Escaneo',
    'biometric.use_pin': 'Usar PIN de seguridad',
    'biometric.scanning': 'Escaneando...',
    'biometric.verifying': 'Verificando Biometría',
    'biometric.enter_pin': 'Ingresar PIN',
    'biometric.pin_desc': 'Ingresa tu código de 4 dígitos',
    'biometric.confirm_pin': 'Confirmar PIN',
    'biometric.back': 'Volver a biometría',
    'biometric.validated': '¡Validado!', //
    'biometric.confirmed': 'Identidad confirmada',
    'ai.status.title': 'Núcleo de IA Gemini',
    'ai.status.active': 'ACTIVO - FREE TIER',
    'ai.status.model': 'Modelo: Gemini 1.5 Flash',
    'ai.status.latency': 'Latencia: Optimizada',
    'maps.status.title': 'Servicios de Mapas',
    'maps.status.active': 'ACTIVO - FREE TIER',
    'maps.status.provider': 'Google Maps Platform',
    'maps.status.quota': 'Cuota: Premium Free',
    'maps.tag.public': 'Red Pública (MINSA)',
    'maps.tag.private': 'Red Privada (Suscripción)',
    'maps.filter.public': 'Solo Sector Público',
    'maps.filter.private': 'Añadir Red Privada',
    'maps.social_mission.title': 'Misión Social de Salud Conecta',
    'maps.social_mission.desc': 'Estamos comprometidos con el acceso a la salud para todos. Si eres usuario Free, te conectamos con toda la Red Pública de Salud de Nicaragua sin costo alguno.', //
    'maps.key_required.title': 'Llave de Google Maps Requerida',
    'maps.key_required.desc': 'No se detectó VITE_GOOGLE_MAPS_API_KEY. Verifica tu archivo .env y reinicia el servidor de desarrollo.',
    'maps.key_required.step1': 'Obtén una llave en',
    'maps.key_required.step2_prefix': 'Agrégala en',
    'maps.key_required.step2_middle': 'con el nombre',
    'maps.key_required.rebuild': 'La aplicación se reiniciará automáticamente al guardar el secreto.',
    'ai.tip.title': 'Consejo de Salud IA',
    'ai.tip.loading': 'Generando consejo personalizado...', //
    'login.hero_title': 'El futuro de la salud en tus manos.',
    'login.hero_desc': 'Únete a Salud Conecta IA y accede a un ecosistema inteligente diseñado para cuidar de ti y de los tuyos en Nicaragua.',
    'login.feat.doctors': 'Red de Médicos',
    'login.feat.challenges': 'Retos Activos',
    'login.feat.care': 'Cuidado Virtual',
    'login.feat.privacy': 'Privacidad Total',
    'login.welcome': 'Bienvenido',
    'login.subtitle': 'Ingresa tus credenciales para continuar.',
    'login.forgot': '¿La olvidaste?',
    'login.btn': 'Iniciar Sesión', //
    'login.or': 'O continúa con',
    'login.no_account': '¿No tienes una cuenta?',
    'login.signup': 'Regístrate gratis',
    'settings.title': 'Ajustes y Personalización',
    'settings.subtitle': 'Gestiona como interactúas con la plataforma y su apariencia.',
    'settings.language': 'Idioma',
    'settings.appearance': 'Apariencia',
    'settings.theme.light': 'Modo Diurno',
    'settings.theme.dark': 'Modo Nocturno',
    'settings.theme.desc.light': 'Fondo claro, alto contraste',
    'settings.theme.desc.dark': 'Tonos profundos, ahorro de batería', //
    'settings.notifications': 'Notificaciones',
    'settings.notif.critical': 'Alertas Médicas (Críticas)',
    'settings.notif.critical.desc': 'Recordatorios ineludibles de medicamentos y confirmaciones urgentes de citas.',
    'settings.notif.challenges': 'Retos de Salud',
    'settings.notif.challenges.desc': 'Motivación diaria, recordatorios de pasos, hidratación y seguimiento de sueño.',
    'settings.notif.benefits': 'Beneficios Premium',
    'settings.notif.benefits.desc': 'Alertas de cupones próximos a vencer, nuevos descuentos y recompensas.',
    'settings.channels': 'Canales de Entrega',
    'settings.channels.push': 'Push (App)',
    'settings.channels.whatsapp': 'WhatsApp',
    'settings.channels.email': 'Correo Electrónico',
    'settings.summary': 'Resumen Diario', //
    'settings.summary.desc': 'Agrupa notificaciones de retos y beneficios en un solo envío diario para reducir distracciones.',
    'settings.summary.time': 'Hora de entrega',
    'settings.save': 'Guardar Cambios',
    'settings.saving': 'Guardando...',
    'settings.processed': '¡Cambios Sincronizados!',
    'settings.processing': 'Procesando...',
    'settings.config.alerts': 'Configuración de Alertas',
    'settings.config.desc': 'Tus cambios se guardan automáticamente en tu bóveda segura.', //
    'settings.theme.light.label': 'Fondo claro, alto contraste',
    'settings.theme.dark.label': 'Tonos profundos, ahorro de batería',
    'settings.channels.push.label': 'Push (App)',
    'settings.channels.whatsapp.label': 'WhatsApp',
    'settings.channels.email.label': 'Correo Electrónico',
    'settings.summary.label': 'Agrupa notificaciones de retos y beneficios en un solo envío diario para reducir distracciones.',
    'settings.notif.critical.label': 'Recomendado mantener activo',
    'wallet.title': 'Puntos de Salud', //
    'wallet.balance': 'Balance Actual',
    'wallet.history': 'Historial Reciente',
    'wallet.rewards': 'Recompensas Premium',
    'hero.badge': 'SISTEMA DE SALUD PÚBLICA INTEGRAL',
    'hero.title': 'Eficiencia {empática} al servicio de tu salud.',
    'hero.subtitle': 'Transformamos la incertidumbre en rutas de acción verificadas. Triaje por IA, mapas de stock y pasaporte digital de salud.',
    'hero.cta.primary': 'Iniciar Triaje IA',
    'hero.cta.secondary': 'Protocolo Realon™',
    'features.title': 'Servicios Integrales',
    'features.1.title': 'Confiabilidad Institucional', //
    'features.1.desc': 'Información verificada directamente de fuentes oficiales de salud pública.',
    'features.2.title': 'Eficiencia Empática',
    'features.2.desc': 'Diseñado para reducir tu carga mental en momentos de necesidad.',
    'features.3.title': 'Acceso Universal',
    'features.3.desc': 'Interfaz optimizada para máxima legibilidad y facilidad de uso.',
    'status.network': 'RED DE SALUD',
    'status.active': 'ACTIVA',
    'status.pharmacies': 'FARMACIAS 24H',
    'status.available': 'DISPONIBLES',
    'status.emergency': 'EMERGENCIAS',
    'status.call': 'LLAMAR',
    'cta.professional.title': '¿Eres un profesional de la salud o regente de farmacia?', //
    'cta.professional.desc': 'Únete a la red interoperable {brand}. Registra tu laboratorio, clínica o farmacia para aparecer en el mapa de stock y disponibilidad en tiempo real.',
    'cta.professional.doctor': 'Soy Profesional',
    'cta.professional.clinic': 'Centro de Salud',
    'cta.professional.business': 'Laboratorio/Farmacia',
    'footer.desc': 'Ecosistema de salud pública inteligente desarrollado para maximizar la eficiencia y empatía en la atención médica nacional.',
    'footer.system': 'Sistema',
    'footer.system.triage': 'Triaje Avanzado',
    'footer.system.pharmacy': 'Red de Farmacias',
    'footer.system.pwa': 'Pasaporte PWA',
    'footer.legal': 'Legal', //
    'footer.legal.privacy': 'Privacidad',
    'footer.legal.terms': 'Términos',
    'footer.legal.acc': 'Accesibilidad',
    'footer.emergency.desc': 'Si siente que su vida está en peligro o tiene síntomas críticos, no use esta herramienta y llame de inmediato al 128 (Cruz Roja) o 115.',
    'pharmacy.badge': 'Miembro Premium',
    'pharmacy.title': 'Descuentos y Beneficios en Farmacias',
    'pharmacy.subtitle': 'Acceso exclusivo a precios preferenciales en medicamentos crónicos y de venta libre en nuestra red de farmacias verificadas.',
    'pharmacy.search_placeholder': 'Buscar medicamentos para ver precios premium...',
    'pharmacy.scan_prescription': 'Escanear Receta',
    'pharmacy.my_coupons': 'Mis Cupones Activos', //
    'pharmacy.verified_title': 'Farmacias Premium Verificadas',
    'pharmacy.view_all': 'Ver todas',
    'pharmacy.qr_code': 'Mostrar QR',
    'pharmacy.expires_in': 'Expira en',
    'pharmacy.card_chronic': 'Tratamiento Crónico',
    'pharmacy.card_general': 'Farmacia General',
    'pharmacy.card_chronic_desc': 'Válido para medicación cardiovascular y metabólica.',
    'pharmacy.card_general_desc': 'Aplica a venta libre y productos de cuidado personal.',
    'activity.title': 'Registros de Actividad',
    'activity.subtitle': 'Tu progreso de salud y retos completados esta semana.', //
    'activity.week': 'Semana',
    'activity.month': 'Mes',
    'activity.daily_progress': 'Progreso Diario',
    'activity.active_challenges': 'Retos Activos',
    'activity.recent': 'Actividad Reciente',
    'activity.view_all': 'Ver historial completo',
    'activity.days': 'días',
    'activity.morning_walk': 'Caminata matutina',
    'activity.today': 'Hoy',
    'activity.hydration_session': 'Sesión de hidratación',
    'activity.yesterday': 'Ayer', //
    'activity.blood_pressure': 'Registro de Presión',
    'activity.monthly_goal_reached_water': 'Meta mensual alcanzada (Agua)',
    'activity.monthly_checkup': 'Chequeo Médico Mensual',
    'activity.5_days_ago': 'Hace 5 días',
    'activity.reward': 'Recompensas',
    'activity.current_progress': 'Progreso Actual',
    'activity.goal': 'Meta',
    'activity.progress': 'Progreso',
    'activity.completed_yesterday': 'Completado ayer',
    'activity.3_days_ago': 'Hace 3 días',
    'stats.total_steps': 'Pasos Totales', //
    'stats.vs_prev_week': 'vs sem. ant.',
    'stats.vs_prev_month': 'vs mes ant.',
    'stats.active_calories': 'Calorías Activas',
    'stats.estimated': 'estimadas',
    'stats.activity_min': 'Min. de Actividad',
    'stats.goal_reached': 'Meta alcanzada',
    'stats.stable_avg': 'Promedio estable',
    'stats.activity': 'actividad',
    'challenges.title': 'Retos de Salud', //
    'challenges.subtitle': 'Completa hábitos saludables para ganar puntos extra y mejorar tu bienestar general.',
    'challenges.weekly': 'Semanales',
    'challenges.monthly': 'Mensuales',
    'challenges.available': 'Retos Disponibles',
    'challenges.join': 'Unirse al Reto',
    'challenges.ranking': 'Ranking Global',
    'challenges.level': 'Nivel',
    'challenges.next_level': 'Sig. Nivel',
    'challenges.sync': 'Sincronizar',
    'challenges.perfect_week': 'Semana Perfecta', //
    'challenges.streak': 'Racha 5 Días',
    'challenges.hero_hydration': 'Héroe de la Hidratación',
    'challenges.hero_hydration_desc': 'Registra 2 litros de agua diarios por 5 días consecutivos.',
    'challenges.restful_sleep': 'Sueño Reparador',
    'challenges.restful_sleep_desc': 'Duerme al menos 7 horas cada noche durante toda la semana.',
    'challenges.active_weekend': 'Fin de Semana Activo',
    'challenges.active_weekend_desc': 'Realiza 60 minutos de actividad física al aire libre este fin de semana.',
    'challenges.marathon': 'Maratón Mensual',
    'challenges.marathon_desc': 'Completa 300,000 pasos en el transcurso del mes.',
    'challenges.sleep_consistency': 'Consistencia de Sueño', //
    'challenges.sleep_consistency_desc': 'Mantén un horario regular de sueño por 4 semanas seguidas.',
    'challenges.mindfulness': 'Mindfulness 30',
    'challenges.mindfulness_desc': 'Realiza 30 sesiones de meditación este mes.',
    'challenges.steps_10k': '10k Pasos Diarios',
    'challenges.steps_10k_desc': 'Mantén un promedio de 10,000 pasos durante toda la semana.',
    'challenges.day_4_of_7': 'Día 4 de 7 consecutivos',
    'challenges.optimal_hydration': 'Hidratación Óptima',
    'challenges.drink_2l_daily_week': 'Bebe 2L diarios (Semana)', //
    'challenges.your_profile': 'Tú Perfil',
    'challenges.current_challenge': 'Reto Actual',
    'challenges.coming_soon': 'Próximos retos en 3 días',
    'challenges.achievements': 'Logros Recientes',
    'challenges.you': 'TÚ',
    'challenges.left_pts': 'Faltan 850 pts',
  },
  en: {
    'nav.triage': 'Triage',
    'nav.pharmacy': 'Pharmacies',
    'nav.search': 'Search',
    'nav.rewards': 'Rewards',
    'nav.activity': 'Challenges',
    'nav.history': 'History',
    'nav.appointments': 'Appointments',
    'nav.membership': 'Membership',
    'nav.dashboard': 'Dashboard',
    'header.emergency': 'Emergency',
    'header.notifications': 'Notifications',
    'header.map': 'Health Map',
    'header.activity': 'Activity & Challenges',
    'profile.title': 'My Health Profile',
    'profile.settings': 'Settings',
    'profile.logout': 'Sign Out',
    'profile.status.frequent': 'Frequent Patient',
    'profile.status.verified': 'Verified Identity',
    'profile.blood': 'Blood Type',
    'profile.allergies': 'Critical Allergy',
    'profile.birth': 'Date of Birth',
    'profile.personal_info': 'Personal Information',
    'profile.validate': 'Validate Identity',
    'profile.validate_desc': 'Biometric validation or PIN is required to edit sensitive information',
    'profile.phone': 'Phone',
    'profile.email': 'Email',
    'profile.address': 'Residential Location',
    'profile.save': 'Save Changes',
    'profile.saving': 'Saving...',
    'profile.docs': 'Medical Documentation',
    'profile.scan': 'Scan Order',
    'profile.sync_error': 'Sync problem',
    'profile.retry': 'Retry',
    'profile.sync_success': 'Document synced successfully',
    'profile.upload_desc': 'Drag or select your files',
    'profile.upload_sub': '(Prescriptions, Reports, Lab • Max 10MB)',
    'profile.select_files': 'Select Files',
    'profile.recent_files': 'Recent Files',
    'profile.emergency_contacts': 'Emergency Contacts',
    'profile.add_contact': 'Add Contact',
    'profile.health_config': 'Health Configuration',
    'profile.sync_cloud': 'Cloud Sync',
    'profile.sync_vault': 'Secure backup in Supabase Vault',
    'profile.local_storage': 'Local Storage (Offline Mode)',
    'profile.indexdb': 'Keep vital cache in IndexedDB',
    'profile.preview': 'Preview',
    'profile.confirm': 'Confirm',
    'profile.cancel': 'Cancel',
    'profile.change_photo': 'Change Photo',
    'profile.passport': 'Digital Sanit Passport',
    'profile.passport_desc': 'Use this code for quick access in clinics and pharmacies of the network.',
    'profile.generate_temp': 'Generate Temporary Access',
    'profile.temp_active': 'Dynamic Access Active',
    'profile.expiry': 'Expires in',
    'profile.not_validated': 'Validate to add contacts',
    'profile.add_trusted': 'Add Trusted Contact',
    'profile.validated_true': 'Identity correctly validated',
    'profile.name_label': 'Name',
    'profile.rel_label': 'Relationship',
    'profile.edit': 'Edit', //
    'profile.delete': 'Delete',
    'profile.encryption': 'End-to-End Encryption',
    'profile.encryption_desc': 'Requires biometric authentication to decrypt medical history and local documents.',
    'profile.encryption_status': 'Encryption Status',
    'profile.system_active': 'SYSTEM ACTIVE',
    'profile.share_temp': 'Share temporary access',
    'profile.code_active': 'Active Code',
    'profile.view_qr': 'View My QR',
    'profile.temp_expiry': 'Temporary code expires in 15 minutes',
    'profile.logout_full': 'Sign Out of Health Session',
    'biometric.title': 'Biometric Validation',
    'biometric.desc': 'Scan your fingerprint or use facial recognition to unlock sensitive data editing.',
    'biometric.start': 'Start Scan',
    'biometric.use_pin': 'Use security PIN',
    'biometric.scanning': 'Scanning...',
    'biometric.verifying': 'Verifying Biometrics',
    'biometric.enter_pin': 'Enter PIN',
    'biometric.pin_desc': 'Enter your 4-digit code',
    'biometric.confirm_pin': 'Confirm PIN',
    'biometric.back': 'Back to biometrics',
    'biometric.validated': 'Validated!', //
    'biometric.confirmed': 'Identity confirmed',
    'ai.status.title': 'Gemini AI Core',
    'ai.status.active': 'ACTIVE - FREE TIER',
    'ai.status.model': 'Model: Gemini 1.5 Flash',
    'ai.status.latency': 'Latency: Optimized',
    'maps.status.title': 'Mapping Services',
    'maps.status.active': 'ACTIVE - FREE TIER',
    'maps.status.provider': 'Google Maps Platform',
    'maps.status.quota': 'Quota: Premium Free',
    'maps.tag.public': 'Public Health Network (MINSA)',
    'maps.tag.private': 'Private Network (Subscription)',
    'maps.filter.public': 'Public Sector Only',
    'maps.filter.private': 'Add Private Network',
    'maps.social_mission.title': 'Salud Conecta Social Mission',
    'maps.social_mission.desc': 'We are committed to health access for all. As a Free user, we connect you with the entire Public Health Network of Nicaragua at no cost.', //
    'maps.key_required.title': 'Google Maps API Key Required',
    'maps.key_required.desc': 'VITE_GOOGLE_MAPS_API_KEY not detected. Check your .env file and restart the development server.',
    'maps.key_required.step1': 'Get a key at',
    'maps.key_required.step2_prefix': 'Add it in',
    'maps.key_required.step2_middle': 'with the name',
    'maps.key_required.rebuild': 'The application will restart automatically after saving the secret.',
    'ai.tip.title': 'AI Health Tip',
    'ai.tip.loading': 'Generating personalized tip...', //
    'login.hero_title': 'The future of health in your hands.',
    'login.hero_desc': 'Join Salud Conecta IA and access an intelligent ecosystem designed to take care of you and your loved ones in Nicaragua.',
    'login.feat.doctors': 'Doctor Network',
    'login.feat.challenges': 'Active Challenges',
    'login.feat.care': 'Virtual Care',
    'login.feat.privacy': 'Total Privacy',
    'login.welcome': 'Welcome',
    'login.subtitle': 'Enter your credentials to continue.',
    'login.forgot': 'Forgot it?',
    'login.btn': 'Sign In', //
    'login.or': 'Or continue with',
    'login.no_account': 'Do not have an account?',
    'login.signup': 'Sign up for free',
    'settings.title': 'Settings & Customization',
    'settings.subtitle': 'Manage how you interact with the platform and its appearance.',
    'settings.language': 'Language',
    'settings.appearance': 'Appearance',
    'settings.theme.light': 'Light Mode',
    'settings.theme.dark': 'Dark Mode',
    'settings.theme.desc.light': 'Light background, high contrast',
    'settings.theme.desc.dark': 'Deep tones, battery saving', //
    'settings.notifications': 'Notifications',
    'settings.notif.critical': 'Medical Alerts (Critical)',
    'settings.notif.critical.desc': 'Unavoidable medication reminders and urgent appointment confirmations.',
    'settings.notif.challenges': 'Health Challenges',
    'settings.notif.challenges.desc': 'Daily motivation, step reminders, hydration and sleep tracking.',
    'settings.notif.benefits': 'Premium Benefits',
    'settings.notif.benefits.desc': 'Alerts for coupons about to expire, new discounts and rewards.',
    'settings.channels': 'Delivery Channels',
    'settings.channels.push': 'Push (App)',
    'settings.channels.whatsapp': 'WhatsApp',
    'settings.channels.email': 'Email',
    'settings.summary': 'Daily Summary', //
    'settings.summary.desc': 'Group challenge and benefit notifications into a single daily delivery to reduce distractions.',
    'settings.summary.time': 'Delivery time',
    'settings.save': 'Save Changes',
    'settings.saving': 'Saving...',
    'settings.processed': 'Changes Synchronized!',
    'settings.processing': 'Processing...',
    'settings.config.alerts': 'Alert Configuration',
    'settings.config.desc': 'Your changes are automatically saved in your secure vault.', //
    'settings.theme.light.label': 'Light background, high contrast',
    'settings.theme.dark.label': 'Deep tones, battery saving',
    'settings.channels.push.label': 'Push (App)',
    'settings.channels.whatsapp.label': 'WhatsApp',
    'settings.channels.email.label': 'Email',
    'settings.summary.label': 'Group challenge and benefit notifications into a single daily delivery to reduce distractions.',
    'settings.notif.critical.label': 'Recommended to keep active',
    'wallet.title': 'Health Points', //
    'wallet.balance': 'Current Balance',
    'wallet.history': 'Recent History',
    'wallet.rewards': 'Premium Rewards',
    'hero.badge': 'INTEGRAL PUBLIC HEALTH SYSTEM',
    'hero.title': 'Empathetic {efficiency} at your health\'s service.',
    'hero.subtitle': 'We transform uncertainty into verified action routes. AI Triage, stock maps, and digital health passport.',
    'hero.cta.primary': 'Start AI Triage',
    'hero.cta.secondary': 'Realon™ Protocol',
    'features.title': 'Comprehensive Services',
    'features.1.title': 'Institutional Reliability', //
    'features.1.desc': 'Information verified directly from official public health sources.',
    'features.2.title': 'Empathetic Efficiency',
    'features.2.desc': 'Designed to reduce your mental load in times of need.',
    'features.3.title': 'Universal Access',
    'features.3.desc': 'Interface optimized for maximum readability and ease of use.',
    'status.network': 'HEALTH NETWORK',
    'status.active': 'ACTIVE',
    'status.pharmacies': '24H PHARMACIES',
    'status.available': 'AVAILABLE',
    'status.emergency': 'EMERGENCIES',
    'status.call': 'CALL',
    'cta.professional.title': 'Are you a healthcare professional or pharmacy manager?', //
    'cta.professional.desc': 'Join the interoperable {brand} network. Register your lab, clinic or pharmacy to appear on the real-time stock and availability map.',
    'cta.professional.doctor': 'I am Professional',
    'cta.professional.clinic': 'Health Center',
    'cta.professional.business': 'Lab/Pharmacy',
    'footer.desc': 'Intelligent public health ecosystem developed to maximize efficiency and empathy in national healthcare.',
    'footer.system': 'System',
    'footer.system.triage': 'Advanced Triage',
    'footer.system.pharmacy': 'Pharmacy Network',
    'footer.system.pwa': 'PWA Passport',
    'footer.legal': 'Legal', //
    'footer.legal.privacy': 'Privacy',
    'footer.legal.terms': 'Terms',
    'footer.legal.acc': 'Accessibility',
    'footer.emergency.desc': 'If you feel your life is in danger or have critical symptoms, do not use this tool and call 128 (Red Cross) or 115 immediately.',
    'pharmacy.badge': 'Premium Member',
    'pharmacy.title': 'Pharmacy Discounts & Benefits',
    'pharmacy.subtitle': 'Exclusive access to preferential prices on chronic and over-the-counter medications in our network of verified pharmacies.',
    'pharmacy.search_placeholder': 'Search medications to see premium prices...',
    'pharmacy.scan_prescription': 'Scan Prescription',
    'pharmacy.my_coupons': 'My Active Coupons', //
    'pharmacy.verified_title': 'Verified Premium Pharmacies',
    'pharmacy.view_all': 'View all',
    'pharmacy.qr_code': 'Show QR',
    'pharmacy.expires_in': 'Expires in',
    'pharmacy.card_chronic': 'Chronic Treatment',
    'pharmacy.card_general': 'General Pharmacy',
    'pharmacy.card_chronic_desc': 'Valid for cardiovascular and metabolic medication.',
    'pharmacy.card_general_desc': 'Applies to over-the-counter and personal care products.',
    'activity.title': 'Activity Logs',
    'activity.subtitle': 'Your health progress and challenges completed this week.', //
    'activity.week': 'Week',
    'activity.month': 'Month',
    'activity.daily_progress': 'Daily Progress',
    'activity.active_challenges': 'Active Challenges',
    'activity.recent': 'Recent Activity',
    'activity.view_all': 'View full history',
    'activity.days': 'days',
    'activity.morning_walk': 'Morning walk',
    'activity.today': 'Today',
    'activity.hydration_session': 'Hydration session',
    'activity.yesterday': 'Yesterday', //
    'activity.blood_pressure': 'Blood Pressure Log',
    'activity.monthly_goal_reached_water': 'Monthly goal reached (Water)',
    'activity.monthly_checkup': 'Monthly Medical Checkup',
    'activity.5_days_ago': '5 days ago',
    'activity.reward': 'Rewards',
    'activity.current_progress': 'Current Progress',
    'activity.goal': 'Goal',
    'activity.progress': 'Progress',
    'activity.completed_yesterday': 'Completed yesterday',
    'activity.3_days_ago': '3 days ago',
    'stats.total_steps': 'Total Steps', //
    'stats.vs_prev_week': 'vs prev week',
    'stats.vs_prev_month': 'vs prev month',
    'stats.active_calories': 'Active Calories',
    'stats.estimated': 'estimated',
    'stats.activity_min': 'Activity Min.',
    'stats.goal_reached': 'Goal reached',
    'stats.stable_avg': 'Stable average',
    'stats.activity': 'activity',
    'challenges.title': 'Health Challenges', //
    'challenges.subtitle': 'Complete healthy habits to earn extra points and improve your general well-being.',
    'challenges.weekly': 'Weekly',
    'challenges.monthly': 'Monthly',
    'challenges.available': 'Available Challenges',
    'challenges.join': 'Join Challenge',
    'challenges.ranking': 'Global Ranking',
    'challenges.level': 'Level',
    'challenges.next_level': 'Next Level',
    'challenges.sync': 'Sync',
    'challenges.perfect_week': 'Perfect Week', //
    'challenges.streak': '5 Day Streak',
    'challenges.hero_hydration': 'Hydration Hero',
    'challenges.hero_hydration_desc': 'Log 2 liters of water daily for 5 consecutive days.',
    'challenges.restful_sleep': 'Restful Sleep',
    'challenges.restful_sleep_desc': 'Sleep at least 7 hours each night for the entire week.',
    'challenges.active_weekend': 'Active Weekend',
    'challenges.active_weekend_desc': 'Perform 60 minutes of outdoor physical activity this weekend.',
    'challenges.marathon': 'Monthly Marathon',
    'challenges.marathon_desc': 'Complete 300,000 steps during the month.',
    'challenges.sleep_consistency': 'Sleep Consistency', //
    'challenges.sleep_consistency_desc': 'Maintain a regular sleep schedule for 4 weeks in a row.',
    'challenges.mindfulness': 'Mindfulness 30',
    'challenges.mindfulness_desc': 'Perform 30 meditation sessions this month.',
    'challenges.steps_10k': '10k Daily Steps',
    'challenges.steps_10k_desc': 'Maintain an average of 10,000 steps throughout the week.',
    'challenges.day_4_of_7': 'Day 4 of 7 consecutive',
    'challenges.optimal_hydration': 'Optimal Hydration',
    'challenges.drink_2l_daily_week': 'Drink 2L daily (Week)', //
    'challenges.your_profile': 'Your Profile',
    'challenges.current_challenge': 'Current Challenge',
    'challenges.coming_soon': 'Next challenges in 3 days',
    'challenges.achievements': 'Recent Achievements',
    'challenges.you': 'YOU',
    'challenges.left_pts': '850 pts left',
  }
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    return (localStorage.getItem('language') as Language) || 'es';
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('language', lang);
  };

  const t = (key: string) => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
