import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'es' | 'en';

interface Translations {
  [key: string]: {
    [key: string]: string;
  };
}

const translations: Translations = {
  es: {
    'nav.triage': 'Consulta',
    'nav.pharmacy': 'Farmacias',
    'nav.search': 'Buscar',
    'nav.rewards': 'Premios',
    'nav.activity': 'Retos',
    'nav.history': 'Historial',
    'nav.appointments': 'Citas',
    'nav.membership': 'Membresía',
    'nav.dashboard': 'Panel',
    'header.emergency': 'Emergencia',
    'header.notifications': 'Notificaciones',
    'header.map': 'Mapa de Salud',
    'header.activity': 'Actividad y Retos',
    'profile.title': 'Mi Perfil de Salud',
    'profile.settings': 'Ajustes',
    'profile.logout': 'Cerrar Sesión',
    'profile.status.frequent': 'Paciente Frecuente',
    'profile.status.verified': 'Identidad Verificada',
    'profile.blood': 'Grupo Sanguíneo',
    'profile.allergies': 'Alergia Crítica',
    'profile.birth': 'Nacimiento',
    'profile.personal_info': 'Información Personal',
    'profile.validate': 'Validar Identidad',
    'profile.validate_desc': 'Se requiere validación biométrica o PIN para editar información sensible',
    'profile.phone': 'Teléfono',
    'profile.email': 'Correo Electrónico',
    'profile.address': 'Ubicación Residencial',
    'profile.save': 'Guardar Cambios',
    'profile.saving': 'Guardando...',
    'profile.docs': 'Documentación Médica',
    'profile.scan': 'Digitalizar Orden',
    'profile.sync_error': 'Problema al sincronizar',
    'profile.retry': 'Intentar de nuevo',
    'profile.sync_success': 'Documento sincronizado con éxito',
    'profile.upload_desc': 'Arrastra o selecciona tus archivos',
    'profile.upload_sub': '(Recetas, Informes, Laboratorio • Máx 10MB)',
    'profile.select_files': 'Seleccionar Archivos',
    'profile.recent_files': 'Archivos Recientes',
    'profile.emergency_contacts': 'Contactos de Emergencia',
    'profile.add_contact': 'Añadir Contacto',
    'profile.rel_label': 'Parentesco',
    'profile.add_trusted': 'Agregar Contacto de Confianza',
    'profile.not_validated': 'Validar identidad para modificar',
    'profile.health_config': 'Configuración de Salud',
    'profile.validated_true': 'Identidad validada. Tienes acceso total.',
    'profile.sync_cloud': 'Sincronización en la Nube',
    'profile.sync_vault': 'Copia de seguridad encriptada en SaludVault',
    'profile.local_storage': 'Almacenamiento Local',
    'profile.indexdb': 'Datos cacheados para uso offline',
    'profile.passport': 'Pasaporte de Salud Digital',
    'profile.share_temp': 'Comparte tu historial temporalmente',
    'profile.code_active': 'CÓDIGO ACTIVO',
    'profile.generate_temp': 'Generar Acceso Temporal',
    'profile.view_qr': 'Ver QR Permanente',
    'profile.temp_expiry': 'El acceso temporal expirará automáticamente en 15 minutos.',
    'profile.encryption': 'Encriptación Activa',
    'profile.encryption_desc': 'Tus datos médicos están protegidos con encriptación de grado militar AES-256. Solo tú y los profesionales autorizados pueden acceder a ellos.',
    'profile.encryption_status': 'ESTADO DEL SISTEMA',
    'profile.system_active': 'SISTEMA ACTIVO',
    'profile.logout_full': 'Cerrar Sesión Segura',
    'profile.photo_uploaded': 'Foto cargada. Recuerda guardar los cambios.',
    'profile.upload_error': 'Error de conexión: No se pudo establecer contacto con el servidor de archivos Realon™. Por favor, intente de nuevo.',
    'profile.doc_scanned': 'Orden digitalizada y guardada',
    'profile.profile_updated': 'Perfil actualizado correctamente',
    'profile.contact_added': 'Contacto de emergencia añadido',
    'profile.expire_in': 'Expira en {time} min',
    'profile.placeholder_name': 'Ej: Maria Garcia',
    'profile.placeholder_rel': 'Ej: Esposa',
    'profile.positive': 'Positivo',
    'profile.negative': 'Negativo',
    'checkout.back': 'Volver a Planes',
    'checkout.title': 'Pago Seguro',
    'checkout.subtitle': 'Completa tu suscripción premium para desbloquear herramientas clínicas avanzadas.',
    'checkout.method': 'Método de Pago',
    'checkout.card': 'Tarjeta de Crédito',
    'checkout.wallet': 'Billetera Digital',
    'checkout.encryption': 'Encriptación de 256 bits',
    'checkout.cardholder': 'Titular de la Tarjeta',
    'checkout.cardholder_placeholder': 'Ej: Dr. Julián Rossi',
    'checkout.card_number': 'Número de Tarjeta',
    'checkout.expiry': 'Vencimiento',
    'checkout.security_msg': 'Tus datos están protegidos bajo los estándares de seguridad bancaria más estrictos. Salud Conecta IA no almacena tu número completo de tarjeta.',
    'checkout.plan_selected': 'Plan Seleccionado',
    'checkout.monthly_billing': 'Facturación Mensual',
    'checkout.subtotal': 'Subtotal',
    'checkout.taxes': 'Impuestos Estimados (8.5%)',
    'checkout.total': 'Total',
    'checkout.processing': 'Procesando...',
    'checkout.confirm': 'Confirmar y Suscribirme',
    'checkout.terms': 'Al confirmar, aceptas nuestros ',
    'checkout.terms_link': 'Términos de Servicio',
    'checkout.and': ' y ',
    'checkout.privacy_link': 'Política de Privacidad',
    'checkout.social_proof': 'Únete a más de 12,000 profesionales médicos que optimizan su práctica diaria con Salud Conecta IA.',
    'reports.download': 'Descargar PDF',
    'profile.preview': 'Vista Previa',
    'profile.confirm': 'Confirmar',
    'profile.cancel': 'Cancelar',
    'profile.change_photo': 'Cambiar Foto',
    'profile.name_label': 'Nombre',
    'profile.edit': 'Editar', //
    'profile.delete': 'Eliminar',
    'biometric.title': 'Validación Biométrica',
    'biometric.desc': 'Escanea tu huella o usa el reconocimiento facial para desbloquear la edición de datos sensibles.',
    'biometric.start': 'Iniciar Escaneo',
    'biometric.use_pin': 'Usar PIN de seguridad',
    'biometric.scanning': 'Escaneando...',
    'biometric.verifying': 'Verificando Biometría',
    'biometric.enter_pin': 'Ingresar PIN',
    'biometric.pin_desc': 'Ingresa tu código de 4 dígitos',
    'biometric.confirm_pin': 'Confirmar PIN',
    'biometric.back': 'Volver a biometría',
    'biometric.validated': '¡Validado!', //
    'biometric.confirmed': 'Identidad confirmada',
    'ai.status.title': 'Núcleo de IA Gemini',
    'ai.status.active': 'ACTIVO - FREE TIER',
    'ai.status.model': 'Modelo: Gemini 1.5 Flash',
    'ai.status.latency': 'Latencia: Optimizada',
    'maps.status.title': 'Servicios de Mapas',
    'maps.status.active': 'ACTIVO - FREE TIER',
    'maps.status.provider': 'Google Maps Platform',
    'maps.status.quota': 'Cuota: Premium Free',
    'maps.tag.public': 'Red Pública (MINSA)',
    'maps.tag.private': 'Red Privada (Suscripción)',
    'maps.filter.public': 'Solo Sector Público',
    'maps.filter.private': 'Añadir Red Privada',
    'maps.social_mission.title': 'Misión Social de Salud Conecta IA',
    'maps.social_mission.desc': 'Estamos comprometidos con el acceso a la salud para todos. Si eres usuario Free, te conectamos con toda la Red Pública de Salud de Nicaragua sin costo alguno.', //
    'maps.key_required.title': 'Llave de Google Maps Requerida',
    'maps.key_required.desc': 'No se detectó VITE_GOOGLE_MAPS_API_KEY. Verifica tu archivo .env y reinicia el servidor de desarrollo.',
    'maps.key_required.step1': 'Obtén una llave en',
    'maps.key_required.step2_prefix': 'Agrégala en',
    'maps.key_required.step2_middle': 'con el nombre',
    'maps.key_required.rebuild': 'La aplicación se reiniciará automáticamente al guardar el secreto.',
    'ai.tip.title': 'Consejo de Salud IA',
    'ai.tip.loading': 'Generando consejo personalizado...', //
    'login.hero_title': 'El futuro de la salud en tus manos.',
    'login.hero_desc': 'Únete a Salud Conecta IA y accede a un ecosistema inteligente diseñado para cuidar de ti y de los tuyos en Nicaragua.',
    'login.feat.doctors': 'Red de Médicos',
    'login.feat.challenges': 'Retos Activos',
    'login.feat.care': 'Cuidado Virtual',
    'login.feat.privacy': 'Privacidad Total',
    'login.welcome': 'Bienvenido',
    'login.subtitle': 'Ingresa tus credenciales para continuar.',
    'login.forgot': '¿La olvidaste?',
    'login.btn': 'Iniciar Sesión', //
    'login.or': 'O continúa con',
    'login.no_account': '¿No tienes una cuenta?',
    'login.signup': 'Regístrate gratis',
    'login.error_invalid': 'Correo o contraseña incorrectos',
    'login.error_general': 'Error al iniciar sesión. Inténtalo de nuevo.',
    'login.error_google': 'Error al conectar con Google.',
    'login.password': 'Contraseña',
    'registration.doctor.premium': 'Médico Premium',
    'registration.clinic.premium': 'Clínica Privada Premium',
    'registration.establishment.premium': 'Establecimiento Premium',
    'registration.no_address': 'Dirección no especificada',
    'registration.doctor.desc': 'Médico profesional premium verificado en la red de Salud Conecta IA.',
    'registration.establishment.desc': 'Establecimiento de salud premium certificado.',
    'registration.validation.title': 'Validación en Proceso',
    'registration.validation.desc': 'Nuestra Inteligencia Artificial está analizando los documentos subidos de forma segura para verificar tus credenciales.',
    'registration.validation.step1': 'Recepción de documentos',
    'registration.validation.step2': 'Analizando autenticidad...',
    'registration.validation.step3': 'Verificando Registro Sanitario',
    'registration.validation.estimation': 'Estimación: 2-5 minutos',
    'registration.next.title': '¿Qué sigue?',
    'registration.next.feature1.title': 'Consulta Avanzada',
    'registration.next.feature1.desc': 'Acceso a herramientas de IA para pre-diagnóstico.',
    'registration.next.feature2.title': 'Recetas Digitales',
    'registration.next.feature2.desc': 'Emisión segura de prescripciones electrónicas.',
    'registration.next.feature3.title': 'Visibilidad Premium',
    'registration.next.feature3.desc': 'Perfil profesional validado en nuestra red.',
    'registration.actions.explore': 'Explorar la red',
    'registration.actions.dashboard': 'Ver Dashboard (Demo)',
    'registration.actions.notify': 'Notificarme al terminar',
    'registration.header.mode': 'Modo de Registro Activo - Ingreso de Nuevas Entidades',
    'registration.header.title': 'Registro de Entidad',
    'registration.titles.doctor': 'Alta de Profesional',
    'registration.titles.clinic': 'Registro Institucional',
    'registration.titles.establishment': 'Datos del Establecimiento',
    'registration.desc.doctor': 'Complete sus credenciales para unirse a la red de atención médica potenciada por IA.',
    'registration.desc.clinic': 'Alta en la red nacional de emergencias y derivaciones.',
    'registration.desc.establishment': 'Complete la información requerida para registrar el laboratorio o farmacia en la red.',
    'registration.form.identity': 'Identidad',
    'registration.form.center_data': 'Datos del Centro',
    'registration.form.official_id': 'Identificación Oficial',
    'registration.form.first_name': 'Nombre(s)',
    'registration.form.last_name': 'Apellidos',
    'registration.form.contact_phone': 'Teléfono de Contacto',
    'registration.form.institution_name': 'Nombre de la Institución',
    'registration.form.center_type': 'Tipo de Centro',
    'registration.form.type_private_hospital': 'Hospital Privado',
    'registration.form.business_name': 'Razón Social',
    'registration.form.establishment_type': 'Tipo de Establecimiento',
    'registration.form.cuit': 'CUIT / Registro Sanitario',
    'registration.form.phone': 'Teléfono',
    'registration.form.credentials': 'Credenciales Clínicas',
    'registration.form.main_specialty': 'Especialidad Principal',
    'registration.form.select_specialty': 'Seleccione una especialidad...',
    'registration.form.professional_license': 'Matrícula Profesional',
    'registration.form.years_experience': 'Años de Experiencia',
    'registration.form.validation_title': 'Validación de Credenciales',
    'registration.form.upload_license': 'Carga de Matrícula Profesional',
    'registration.form.drag_file': 'Arrastre su archivo aquí',
    'registration.form.file_format': 'PDF, JPG, PNG (Máx 5MB)',
    'registration.form.upload_btn': 'Subir archivo',
    'registration.form.pending_upload': 'Pendiente de carga',
    'registration.form.medical_degree': 'Título Médico Habilitante',
    'registration.form.drag_degree': 'Arrastre su título aquí',
    'registration.form.legalized_copy': 'Copia legalizada (Máx 10MB)',
    'registration.form.capabilities': 'Capacidades',
    'registration.form.offered_specialties': 'Especialidades Ofrecidas',
    'registration.form.contact': 'Contacto',
    'registration.form.emergency_phone': 'Teléfono de Emergencias (24hs)',
    'registration.form.medical_director': 'Director Médico Responsable',
    'registration.form.available_services': 'Servicios Disponibles',
    'registration.form.attention_hours': 'Horario de Atención',
    'registration.form.opening': 'Apertura',
    'registration.form.closing': 'Cierre',
    'registration.form.open_24h_active': 'Atención 24 Horas (Guardia Activa)',
    'registration.form.location': 'Ubicación',
    'registration.form.detect_location': 'Detectar Ubicación',
    'registration.form.address_doctor': 'Dirección Física / Consultorio',
    'registration.form.address_clinic': 'Dirección Institucional',
    'registration.form.address_full': 'Dirección Completa',
    'registration.form.address_doctor_ph': 'Ej. Av. Principal 123, Consultorio 4B',
    'registration.form.address_full_ph': 'Calle, Número, Piso, Localidad',
    'registration.form.latitude': 'Latitud',
    'registration.form.longitude': 'Longitud',
    'registration.form.finish_doctor': 'Finalizar Registro',
    'registration.form.finish_clinic': 'Registrar Institución',
    'registration.form.finish_establishment': 'Registrar Entidad',
    'registration.form.cancel': 'Cancelar',
    'registration.form.encrypted_info': 'Información Encriptada',
    'settings.title': 'Ajustes y Personalización',
    'settings.subtitle': 'Gestiona como interactúas con la plataforma y su apariencia.',
    'settings.language': 'Idioma',
    'settings.appearance': 'Apariencia',
    'settings.theme.light': 'Modo Diurno',
    'settings.theme.dark': 'Modo Nocturno',
    'settings.theme.desc.light': 'Fondo claro, alto contraste',
    'settings.theme.desc.dark': 'Tonos profundos, ahorro de batería', //
    'appointments.access_reserved': 'Acceso Reservado',
    'appointments.login_prompt': 'Para gestionar tus citas y ver tu historial médico, por favor inicia sesión de forma segura.',
    'appointments.sync_data': 'Sincronizar Datos',
    'appointments.title': 'Gestión de Citas',
    'appointments.desc': 'Administre sus próximas consultas y revise su historial médico sincronizado por IA.',
    'appointments.new_appointment': 'Nueva Cita',
    'appointments.search_ph': 'Buscar por médico, especialidad o ubicación...',
    'appointments.filter.all': 'Todos',
    'appointments.filter.doctors': 'Médicos',
    'appointments.filter.labs': 'Laboratorios',
    'appointments.filter.clinics': 'Clínicas',
    'appointments.upcoming': 'Próximas Citas',
    'appointments.scheduled': 'Programadas',
    'appointments.syncing': 'Sincronizando Agenda...',
    'appointments.default_medical': 'Cita Médica',
    'appointments.default_location': 'Hospital Central, Ala Norte',
    'appointments.pending': 'Pendiente',
    'appointments.add_calendar': 'Añadir al calendario',
    'appointments.cancel_appt': 'Cancelar cita',
    'appointments.empty_title': 'Agenda Vacía',
    'appointments.empty_desc': 'No tiene citas programadas en este momento. Inicie una solicitud para agendar su próxima atención.',
    'appointments.schedule_new': 'Programar Nueva Cita',
    'appointments.recent_history': 'Historial Reciente',
    'appointments.view_all_history': 'Ver todo el historial',
    'appointments.no_symptoms': 'Sin síntomas',
    'appointments.date_unavailable': 'Fecha no disponible',
    'appointments.emergency': 'EMERGENCIA',
    'appointments.completed': 'COMPLETADA',
    'appointments.no_history': 'No hay registros de historial recientes.',
    'appointments.view_passport': 'Ver Pasaporte de Salud Completo',
    'appointments.general_doctor': 'Médico General',
    'appointments.laboratory': 'Laboratorio',
    'appointments.need_help': '¿Necesitas ayuda?',
    'appointments.help_desc': 'Si tienes problemas para encontrar una cita o requieres asistencia técnica, contacta a nuestro equipo de atención al paciente.',
    'appointments.contact_support': 'Contactar Soporte',
    'appointments.confirm_cancel': 'Confirmar Cancelación',
    'appointments.cancel_warning': '¿Estás seguro de que deseas cancelar esta cita? Esta acción no se puede deshacer.',
    'appointments.keep_appt': 'Mantener Cita',
    'appointments.yes_cancel': 'Sí, Cancelar',
    'appointment.modal.imported_from_ai': 'Importado de Consulta IA:\nSíntomas: {symptoms}\nRecomendación: {recommendation}',
    'appointment.modal.doctor_name': 'Dra. S. Ramírez',
    'appointment.modal.lab_name': 'Laboratorio Central',
    'appointment.modal.hospital_name': 'Hospital Central, Ala Norte',
    'appointment.modal.title': 'Nueva Cita',
    'appointment.modal.subtitle': 'Complete los detalles para agendar su consulta.',
    'appointment.modal.service_type_label': 'TIPO DE SERVICIO',
    'appointment.modal.medical_consultation': 'Consulta Médica',
    'appointment.modal.lab_analysis': 'Análisis Lab',
    'appointment.modal.specialty': 'Especialidad',
    'appointment.modal.location_professional_label': 'UBICACIÓN / PROFESIONAL',
    'appointment.modal.search_placeholder': 'Buscar por nombre, especialidad o centro...',
    'appointment.modal.nearest': 'Más cercano',
    'appointment.modal.date_time_label': 'FECHA Y HORA',
    'appointment.modal.november_2024': 'Noviembre 2024',
    'appointment.modal.days.mon': 'L',
    'appointment.modal.days.tue': 'M',
    'appointment.modal.days.wed': 'M',
    'appointment.modal.days.thu': 'J',
    'appointment.modal.days.fri': 'V',
    'appointment.modal.days.sat': 'S',
    'appointment.modal.days.sun': 'D',
    'appointment.modal.available_times_prefix': 'Horarios Disponibles - ',
    'appointment.modal.available_times_suffix': ' Nov',
    'appointment.modal.notes_label': 'NOTAS O SÍNTOMAS PREVIOS',
    'appointment.modal.import_triage': 'Importar de Consulta IA',
    'appointment.modal.notes_placeholder': 'Describa brevemente el motivo de su consulta o síntomas...',
    'appointment.modal.cancel': 'Cancelar',
    'appointment.modal.scheduling': 'Agendando...',
    'appointment.modal.confirm': 'Confirmar Cita',
    'chat.simulation.search': 'Buscar o empezar un chat',
    'chat.simulation.name': 'Salud Conecta IA',
    'chat.simulation.subject': 'Confirmación de Cita Médica...',
    'chat.simulation.official': 'Empresa oficial',
    'chat.simulation.today': 'Hoy',
    'chat.simulation.security_msg': 'Las llamadas y mensajes a esta empresa ahora están cifrados de extremo a extremo. Toca para más información.',
    'chat.simulation.message_title': 'Confirmación de Cita Médica',
    'chat.simulation.message_body': 'Hola. Te contactamos de <strong>Salud Conecta IA</strong> para confirmar tu próxima cita médica.',
    'chat.simulation.specialist': 'Especialista',
    'chat.simulation.dr_name': 'Dr. Carlos Mendoza',
    'chat.simulation.dr_specialty': 'Cardiología',
    'chat.simulation.datetime': 'Fecha y Hora',
    'chat.simulation.date': 'Viernes, 15 Noviembre',
    'chat.simulation.time': '09:00 AM',
    'chat.simulation.location_label': 'Ubicación',
    'chat.simulation.location': 'Hospital Central, Torre B, Consultorio 402.',
    'chat.simulation.open_maps': 'Abrir en Google Maps',
    'chat.simulation.important_instructions': 'Instrucciones importantes',
    'chat.simulation.instruction1': 'Presentarse con <strong>ayuno de 8 horas</strong>.',
    'chat.simulation.instruction2': 'Llevar <strong>estudios previos</strong> relevantes.',
    'chat.simulation.instruction3': 'Llegar 15 minutos antes.',
    'chat.simulation.confirm_prompt': 'Por favor, confirma tu asistencia usando el botón de abajo.',
    'chat.simulation.btn_confirm': 'Confirmar asistencia',
    'chat.simulation.btn_cancel': 'Cancelar o reagendar',
    'chat.simulation.user_reply': 'Perfecto, allí estaré. Muchas gracias por el recordatorio.',
    'chat.simulation.input_placeholder': 'Escribe un mensaje',
    'chat.assistant.greeting': 'Hola. Soy tu asistente de Salud Conecta IA. ¿En qué puedo ayudarte hoy?',
    'chat.assistant.title': 'Asistente de Salud Conecta IA',
    'chat.assistant.subtitle': 'Empático y Eficiente • Disponible 24/7',
    'chat.assistant.role_ai': 'Asistente IA',
    'chat.assistant.role_user': 'Tú',
    'chat.assistant.thinking': 'Pensando...',
    'chat.assistant.input_placeholder': 'Escribe tu consulta aquí...',
    'chat.assistant.disclaimer': 'La IA puede cometer errores. Verifica la información importante.',
    'settings.notifications': 'Notificaciones',
    'settings.notif.critical': 'Alertas Médicas (Críticas)',
    'settings.notif.critical.desc': 'Recordatorios ineludibles de medicamentos y confirmaciones urgentes de citas.',
    'settings.notif.challenges': 'Retos de Salud',
    'settings.notif.challenges.desc': 'Motivación diaria, recordatorios de pasos, hidratación y seguimiento de sueño.',
    'settings.notif.benefits': 'Beneficios Premium',
    'settings.notif.benefits.desc': 'Alertas de cupones próximos a vencer, nuevos descuentos y recompensas.',
    'settings.channels': 'Canales de Entrega',
    'settings.channels.push': 'Push (App)',
    'settings.channels.whatsapp': 'WhatsApp',
    'settings.channels.email': 'Correo Electrónico',
    'settings.summary': 'Resumen Diario', //
    'settings.summary.desc': 'Agrupa notificaciones de retos y beneficios en un solo envío diario para reducir distracciones.',
    'settings.summary.time': 'Hora de entrega',
    'settings.save': 'Guardar Cambios',
    'settings.saving': 'Guardando...',
    'settings.processed': '¡Cambios Sincronizados!',
    'settings.processing': 'Procesando...',
    'settings.config.alerts': 'Configuración de Alertas',
    'settings.config.desc': 'Tus cambios se guardan automáticamente en tu bóveda segura.', //
    'settings.theme.light.label': 'Fondo claro, alto contraste',
    'settings.theme.dark.label': 'Tonos profundos, ahorro de batería',
    'settings.channels.push.label': 'Push (App)',
    'settings.channels.whatsapp.label': 'WhatsApp',
    'settings.channels.email.label': 'Correo Electrónico',
    'settings.summary.label': 'Agrupa notificaciones de retos y beneficios en un solo envío diario para reducir distracciones.',
    'settings.notif.critical.label': 'Recomendado mantener activo',
    'wallet.title': 'Puntos de Salud', //
    'wallet.balance': 'Balance Actual',
    'wallet.history': 'Historial Reciente',
    'wallet.rewards': 'Recompensas Premium',
    'hero.badge': 'SISTEMA DE SALUD PÚBLICA INTEGRAL',
    'hero.title': 'Eficiencia {empática} al servicio de tu salud.',
    'hero.subtitle': 'Transformamos la incertidumbre en rutas de acción verificadas. Consulta por IA, mapas de stock y pasaporte digital de salud.',
    'hero.cta.primary': 'Iniciar Consulta IA',
    'hero.cta.secondary': 'Protocolo Realon™',
    'features.title': 'Servicios Integrales',
    'features.1.title': 'Confiabilidad Institucional', //
    'features.1.desc': 'Información verificada directamente de fuentes oficiales de salud pública.',
    'features.2.title': 'Eficiencia Empática',
    'features.2.desc': 'Diseñado para reducir tu carga mental en momentos de necesidad.',
    'features.3.title': 'Acceso Universal',
    'features.3.desc': 'Interfaz optimizada para máxima legibilidad y facilidad de uso.',
    'status.network': 'RED DE SALUD',
    'status.active': 'ACTIVA',
    'status.pharmacies': 'FARMACIAS 24H',
    'status.available': 'DISPONIBLES',
    'status.emergency': 'EMERGENCIAS',
    'status.call': 'LLAMAR',
    'cta.professional.title': '¿Eres un profesional de la salud o regente de farmacia?', //
    'cta.professional.desc': 'Únete a la red interoperable {brand}. Registra tu laboratorio, clínica o farmacia para aparecer en el mapa de stock y disponibilidad en tiempo real.',
    'cta.professional.doctor': 'Soy Profesional',
    'cta.professional.clinic': 'Centro de Salud',
    'cta.professional.business': 'Laboratorio/Farmacia',
    'footer.desc': 'Ecosistema de salud pública inteligente desarrollado para maximizar la eficiencia y empatía en la atención médica nacional.',
    'footer.system': 'Sistema',
    'footer.system.triage': 'Consulta Avanzada',
    'footer.system.pharmacy': 'Red de Farmacias',
    'footer.system.pwa': 'Pasaporte PWA',
    'footer.legal': 'Legal', //
    'footer.legal.privacy': 'Privacidad',
    'footer.legal.terms': 'Términos',
    'footer.legal.acc': 'Accesibilidad',
    'footer.emergency.desc': 'Si siente que su vida está en peligro o tiene síntomas críticos, no use esta herramienta y llame de inmediato al 128 (Cruz Roja) o 115.',
    'pharmacy.badge': 'Miembro Premium',
    'pharmacy.title': 'Descuentos y Beneficios en Farmacias',
    'pharmacy.subtitle': 'Acceso exclusivo a precios preferenciales en medicamentos crónicos y de venta libre en nuestra red de farmacias verificadas.',
    'pharmacy.search_placeholder': 'Buscar medicamentos para ver precios premium...',
    'pharmacy.scan_prescription': 'Escanear Receta',
    'pharmacy.my_coupons': 'Mis Cupones Activos', //
    'pharmacy.verified_title': 'Farmacias Premium Verificadas',
    'pharmacy.view_all': 'Ver todas',
    'pharmacy.qr_code': 'Mostrar QR',
    'pharmacy.expires_in': 'Expira en',
    'pharmacy.card_chronic': 'Tratamiento Crónico',
    'pharmacy.card_general': 'Farmacia General',
    'pharmacy.card_chronic_desc': 'Válido para medicación cardiovascular y metabólica.',
    'pharmacy.card_general_desc': 'Aplica a venta libre y productos de cuidado personal.',
    'activity.title': 'Registros de Actividad',
    'activity.subtitle': 'Tu progreso de salud y retos completados esta semana.', //
    'activity.week': 'Semana',
    'activity.month': 'Mes',
    'activity.daily_progress': 'Progreso Diario',
    'activity.active_challenges': 'Retos Activos',
    'activity.recent': 'Actividad Reciente',
    'activity.view_all': 'Ver historial completo',
    'activity.days': 'días',
    'activity.morning_walk': 'Caminata matutina',
    'activity.today': 'Hoy',
    'activity.hydration_session': 'Sesión de hidratación',
    'activity.yesterday': 'Ayer', //
    'activity.blood_pressure': 'Registro de Presión',
    'activity.monthly_goal_reached_water': 'Meta mensual alcanzada (Agua)',
    'activity.monthly_checkup': 'Chequeo Médico Mensual',
    'activity.5_days_ago': 'Hace 5 días',
    'activity.reward': 'Recompensas',
    'activity.current_progress': 'Progreso Actual',
    'activity.goal': 'Meta',
    'activity.progress': 'Progreso',
    'activity.completed_yesterday': 'Completado ayer',
    'activity.3_days_ago': 'Hace 3 días',
    'stats.total_steps': 'Pasos Totales', //
    'stats.vs_prev_week': 'vs sem. ant.',
    'stats.vs_prev_month': 'vs mes ant.',
    'stats.active_calories': 'Calorías Activas',
    'stats.estimated': 'estimadas',
    'stats.activity_min': 'Min. de Actividad',
    'stats.goal_reached': 'Meta alcanzada',
    'stats.stable_avg': 'Promedio estable',
    'stats.activity': 'actividad',
    'challenges.title': 'Retos de Salud', //
    'challenges.subtitle': 'Completa hábitos saludables para ganar puntos extra y mejorar tu bienestar general.',
    'challenges.weekly': 'Semanales',
    'challenges.monthly': 'Mensuales',
    'challenges.available': 'Retos Disponibles',
    'challenges.join': 'Unirse al Reto',
    'challenges.ranking': 'Ranking Global',
    'challenges.level': 'Nivel',
    'challenges.next_level': 'Sig. Nivel',
    'challenges.sync': 'Sincronizar',
    'challenges.perfect_week': 'Semana Perfecta', //
    'challenges.streak': 'Racha 5 Días',
    'challenges.hero_hydration': 'Héroe de la Hidratación',
    'challenges.hero_hydration_desc': 'Registra 2 litros de agua diarios por 5 días consecutivos.',
    'challenges.restful_sleep': 'Sueño Reparador',
    'challenges.restful_sleep_desc': 'Duerme al menos 7 horas cada noche durante toda la semana.',
    'challenges.active_weekend': 'Fin de Semana Activo',
    'challenges.active_weekend_desc': 'Realiza 60 minutos de actividad física al aire libre este fin de semana.',
    'challenges.marathon': 'Maratón Mensual',
    'challenges.marathon_desc': 'Completa 300,000 pasos en el transcurso del mes.',
    'challenges.sleep_consistency': 'Consistencia de Sueño', //
    'challenges.sleep_consistency_desc': 'Mantén un horario regular de sueño por 4 semanas seguidas.',
    'challenges.mindfulness': 'Mindfulness 30',
    'challenges.mindfulness_desc': 'Realiza 30 sesiones de meditación este mes.',
    'challenges.steps_10k': '10k Pasos Diarios',
    'challenges.steps_10k_desc': 'Mantén un promedio de 10,000 pasos durante toda la semana.',
    'challenges.day_4_of_7': 'Día 4 de 7 consecutivos',
    'challenges.optimal_hydration': 'Hidratación Óptima',
    'challenges.drink_2l_daily_week': 'Bebe 2L diarios (Semana)', //
    'challenges.your_profile': 'Tú Perfil',
    'challenges.current_challenge': 'Reto Actual',
    'challenges.coming_soon': 'Próximos retos en 3 días',
    'challenges.achievements': 'Logros Recientes',
    'challenges.you': 'TÚ',
    'challenges.left_pts': 'Faltan 850 pts',
    'maps.premium.filter_all': 'Todos',
    'maps.premium.filter_hospitals': 'Hospitales',
    'maps.premium.filter_clinics': 'Clínicas',
    'maps.premium.filter_labs': 'Laboratorios',
    'maps.premium.filter_pharmacies': 'Farmacias',
    'maps.premium.type_hospital': 'Hospital Privado',
    'maps.premium.type_clinic': 'Clínica Privada',
    'maps.premium.type_lab': 'Laboratorio',
    'maps.premium.type_pharmacy': 'Farmacia Premium',
    'maps.premium.type_dental': 'Clínica Dental',
    'maps.premium.type_private': 'Servicio Privado',
    'maps.premium.req_title': 'Acceso Premium Requerido',
    'maps.premium.req_subtitle': 'Desbloquea la Red de Salud Privada de Nicaragua',
    'maps.premium.feat_1': 'Clínicas y hospitales privados exclusivos',
    'maps.premium.feat_2': 'Sin filas con turnos priorizados por IA',
    'maps.premium.feat_3': 'Médicos y especialistas recomendados',
    'maps.premium.feat_4': 'Descuentos premium en laboratorios y farmacias',
    'maps.premium.get_now': 'Obtener Premium Ahora',
    'maps.premium.hero_title': 'Red de Salud Premium',
    'maps.premium.hero_subtitle': 'Centros privados y especialistas de primer nivel',
    'maps.premium.exclusive_service': 'Servicio Exclusivo',
    'search.hero_title': 'Encuentra atención médica de calidad',
    'search.hero_subtitle': 'Busca hospitales, clínicas, farmacias y laboratorios cerca de ti',
    'maps.premium.stat_vip': 'Centros VIP',
    'maps.premium.stat_near': 'Cercanos (<5km)',
    'maps.premium.stat_rating': 'Alta Valoración',
    'maps.premium.search_placeholder': 'Buscar clínicas, hospitales o farmacias privadas...',
    'maps.premium.no_results': 'No se encontraron centros',
    'maps.premium.no_results_desc': 'Intenta ajustando los filtros o buscando con otros términos.',
    'maps.premium.24h': '24 Horas',
    'maps.premium.view_profile': 'Ver Perfil',
    'maps.premium.directions': 'Cómo Llegar',
    'maps.premium.prev': 'Anterior',
    'maps.premium.page': 'Página',
    'maps.premium.of': 'de',
    'maps.premium.next': 'Siguiente',
    'maps.premium.red_premium': 'Red Premium',
    'maps.premium.authorized_center': 'Centro Autorizado Premium',
    'maps.premium.about_center': 'Sobre el Centro',
    'maps.premium.about_desc': 'Institución médica privada de primer nivel con equipamiento moderno y atención personalizada.',
    'maps.premium.services': 'Especialidades y Servicios',
    'maps.premium.direct_phone': 'Teléfono de Contacto Directo',
    'maps.premium.location_coords': 'Ubicación',
    'maps.premium.open_maps': 'Abrir en Maps',
    'maps.premium.schedule_turn': 'Agendar Turno'
  },
  en: {
    'nav.triage': 'Triage',
    'nav.pharmacy': 'Pharmacies',
    'nav.search': 'Search',
    'nav.rewards': 'Rewards',
    'nav.activity': 'Challenges',
    'nav.history': 'History',
    'nav.appointments': 'Appointments',
    'nav.membership': 'Membership',
    'nav.dashboard': 'Dashboard',
    'header.emergency': 'Emergency',
    'header.notifications': 'Notifications',
    'header.map': 'Health Map',
    'header.activity': 'Activity & Challenges',
    'profile.title': 'My Health Profile',
    'profile.settings': 'Settings',
    'profile.logout': 'Sign Out',
    'profile.status.frequent': 'Frequent Patient',
    'profile.status.verified': 'Verified Identity',
    'profile.blood': 'Blood Type',
    'profile.allergies': 'Critical Allergy',
    'profile.birth': 'Date of Birth',
    'profile.personal_info': 'Personal Information',
    'profile.validate': 'Validate Identity',
    'profile.validate_desc': 'Biometric validation or PIN is required to edit sensitive information',
    'profile.phone': 'Phone',
    'profile.email': 'Email',
    'profile.address': 'Residential Location',
    'profile.save': 'Save Changes',
    'profile.saving': 'Saving...',
    'profile.docs': 'Medical Documentation',
    'profile.scan': 'Scan Order',
    'profile.sync_error': 'Sync problem',
    'profile.retry': 'Retry',
    'profile.sync_success': 'Document synced successfully',
    'profile.upload_desc': 'Drag or select your files',
    'profile.upload_sub': '(Prescriptions, Reports, Lab • Max 10MB)',
    'profile.select_files': 'Select Files',
    'profile.recent_files': 'Recent Files',
    'profile.emergency_contacts': 'Emergency Contacts',
    'profile.rel_label': 'Relationship',
    'profile.add_contact': 'Add Contact',
    'profile.add_trusted': 'Add Trusted Contact',
    'profile.not_validated': 'Validate identity to modify',
    'profile.health_config': 'Health Configuration',
    'profile.validated_true': 'Identity validated. You have full access.',
    'profile.sync_cloud': 'Cloud Sync',
    'profile.sync_vault': 'Encrypted backup in SaludVault',
    'profile.local_storage': 'Local Storage',
    'profile.indexdb': 'Cached data for offline use',
    'profile.passport': 'Digital Health Passport',
    'profile.share_temp': 'Share your history temporarily',
    'profile.code_active': 'ACTIVE CODE',
    'profile.generate_temp': 'Generate Temporary Access',
    'profile.view_qr': 'View Permanent QR',
    'profile.temp_expiry': 'Temporary access will automatically expire in 15 minutes.',
    'profile.encryption': 'Active Encryption',
    'profile.encryption_desc': 'Your medical data is protected with AES-256 military-grade encryption. Only you and authorized professionals can access it.',
    'profile.encryption_status': 'SYSTEM STATUS',
    'profile.system_active': 'SYSTEM ACTIVE',
    'profile.logout_full': 'Secure Log Out',
    'profile.photo_uploaded': 'Photo uploaded. Remember to save your changes.',
    'profile.upload_error': 'Connection error: Could not contact the Realon™ file server. Please try again.',
    'profile.doc_scanned': 'Order scanned and saved',
    'profile.profile_updated': 'Profile updated successfully',
    'profile.contact_added': 'Emergency contact added',
    'profile.expire_in': 'Expires in {time} min',
    'profile.placeholder_name': 'Ex: Maria Garcia',
    'profile.placeholder_rel': 'Ex: Wife',
    'profile.positive': 'Positive',
    'profile.negative': 'Negative',
    'checkout.back': 'Back to Plans',
    'checkout.title': 'Secure Payment',
    'checkout.subtitle': 'Complete your premium subscription to unlock advanced clinical tools.',
    'checkout.method': 'Payment Method',
    'checkout.card': 'Credit Card',
    'checkout.wallet': 'Digital Wallet',
    'checkout.encryption': '256-bit Encryption',
    'checkout.cardholder': 'Cardholder',
    'checkout.cardholder_placeholder': 'Ex: Dr. Julian Rossi',
    'checkout.card_number': 'Card Number',
    'checkout.expiry': 'Expiry',
    'checkout.security_msg': 'Your data is protected under the strictest bank security standards. Salud Conecta AI does not store your full card number.',
    'checkout.plan_selected': 'Selected Plan',
    'checkout.monthly_billing': 'Monthly Billing',
    'checkout.subtotal': 'Subtotal',
    'checkout.taxes': 'Estimated Taxes (8.5%)',
    'checkout.total': 'Total',
    'checkout.processing': 'Processing...',
    'checkout.confirm': 'Confirm and Subscribe',
    'checkout.terms': 'By confirming, you accept our ',
    'checkout.terms_link': 'Terms of Service',
    'checkout.and': ' and ',
    'checkout.privacy_link': 'Privacy Policy',
    'checkout.social_proof': 'Join over 12,000 medical professionals who optimize their daily practice with Salud Conecta AI.',
    'reports.download': 'Download PDF',
    'profile.preview': 'Preview',
    'profile.confirm': 'Confirm',
    'profile.cancel': 'Cancel',
    'profile.change_photo': 'Change Photo',
    'profile.name_label': 'Name',
    'profile.edit': 'Edit', //
    'profile.delete': 'Delete',
    'biometric.title': 'Biometric Validation',
    'biometric.desc': 'Scan your fingerprint or use facial recognition to unlock sensitive data editing.',
    'biometric.start': 'Start Scan',
    'biometric.use_pin': 'Use security PIN',
    'biometric.scanning': 'Scanning...',
    'biometric.verifying': 'Verifying Biometrics',
    'biometric.enter_pin': 'Enter PIN',
    'biometric.pin_desc': 'Enter your 4-digit code',
    'biometric.confirm_pin': 'Confirm PIN',
    'biometric.back': 'Back to biometrics',
    'biometric.validated': 'Validated!', //
    'biometric.confirmed': 'Identity confirmed',
    'ai.status.title': 'Gemini AI Core',
    'ai.status.active': 'ACTIVE - FREE TIER',
    'ai.status.model': 'Model: Gemini 1.5 Flash',
    'ai.status.latency': 'Latency: Optimized',
    'maps.status.title': 'Mapping Services',
    'maps.status.active': 'ACTIVE - FREE TIER',
    'maps.status.provider': 'Google Maps Platform',
    'maps.status.quota': 'Quota: Premium Free',
    'maps.tag.public': 'Public Health Network (MINSA)',
    'maps.tag.private': 'Private Network (Subscription)',
    'maps.filter.public': 'Public Sector Only',
    'maps.filter.private': 'Add Private Network',
    'maps.social_mission.title': 'Salud Conecta IA Social Mission',
    'maps.social_mission.desc': 'We are committed to health access for all. As a Free user, we connect you with the entire Public Health Network of Nicaragua at no cost.', //
    'maps.key_required.title': 'Google Maps API Key Required',
    'maps.key_required.desc': 'VITE_GOOGLE_MAPS_API_KEY not detected. Check your .env file and restart the development server.',
    'maps.key_required.step1': 'Get a key at',
    'maps.key_required.step2_prefix': 'Add it in',
    'maps.key_required.step2_middle': 'with the name',
    'maps.key_required.rebuild': 'The application will restart automatically after saving the secret.',
    'ai.tip.title': 'AI Health Tip',
    'ai.tip.loading': 'Generating personalized tip...', //
    'login.hero_title': 'The future of health in your hands.',
    'login.hero_desc': 'Join Salud Conecta IA and access an intelligent ecosystem designed to take care of you and your loved ones in Nicaragua.',
    'login.feat.doctors': 'Doctor Network',
    'login.feat.challenges': 'Active Challenges',
    'login.feat.care': 'Virtual Care',
    'login.feat.privacy': 'Total Privacy',
    'login.welcome': 'Welcome',
    'login.subtitle': 'Enter your credentials to continue.',
    'login.forgot': 'Forgot it?',
    'login.btn': 'Sign In', //
    'login.or': 'Or continue with',
    'login.no_account': 'Do not have an account?',
    'login.signup': 'Sign up for free',
    'login.error_invalid': 'Incorrect email or password',
    'login.error_general': 'Error logging in. Try again.',
    'login.error_google': 'Error connecting to Google.',
    'login.password': 'Password',
    'registration.doctor.premium': 'Premium Doctor',
    'registration.clinic.premium': 'Premium Private Clinic',
    'registration.establishment.premium': 'Premium Establishment',
    'registration.no_address': 'Address not specified',
    'registration.doctor.desc': 'Verified premium medical professional in the Salud Conecta AI network.',
    'registration.establishment.desc': 'Certified premium health establishment.',
    'registration.validation.title': 'Validation in Progress',
    'registration.validation.desc': 'Our Artificial Intelligence is analyzing the securely uploaded documents to verify your credentials.',
    'registration.validation.step1': 'Document receipt',
    'registration.validation.step2': 'Analyzing authenticity...',
    'registration.validation.step3': 'Verifying Health Registry',
    'registration.validation.estimation': 'Estimate: 2-5 minutes',
    'registration.next.title': 'What\'s next?',
    'registration.next.feature1.title': 'Advanced Triage',
    'registration.next.feature1.desc': 'Access to AI tools for pre-diagnosis.',
    'registration.next.feature2.title': 'Digital Prescriptions',
    'registration.next.feature2.desc': 'Secure issuance of electronic prescriptions.',
    'registration.next.feature3.title': 'Premium Visibility',
    'registration.next.feature3.desc': 'Verified professional profile in our network.',
    'registration.actions.explore': 'Explore network',
    'registration.actions.dashboard': 'View Dashboard (Demo)',
    'registration.actions.notify': 'Notify me when finished',
    'registration.header.mode': 'Active Registration Mode - Entry of New Entities',
    'registration.header.title': 'Entity Registration',
    'registration.titles.doctor': 'Professional Registration',
    'registration.titles.clinic': 'Institutional Registration',
    'registration.titles.establishment': 'Establishment Data',
    'registration.desc.doctor': 'Complete your credentials to join the AI-powered healthcare network.',
    'registration.desc.clinic': 'Registration in the national emergency and referral network.',
    'registration.desc.establishment': 'Complete the required information to register the lab or pharmacy in the network.',
    'registration.form.identity': 'Identity',
    'registration.form.center_data': 'Center Data',
    'registration.form.official_id': 'Official ID',
    'registration.form.first_name': 'First Name(s)',
    'registration.form.last_name': 'Last Name',
    'registration.form.contact_phone': 'Contact Phone',
    'registration.form.institution_name': 'Institution Name',
    'registration.form.center_type': 'Center Type',
    'registration.form.type_private_hospital': 'Private Hospital',
    'registration.form.business_name': 'Business Name',
    'registration.form.establishment_type': 'Establishment Type',
    'registration.form.cuit': 'Tax ID / Health Registry',
    'registration.form.phone': 'Phone',
    'registration.form.credentials': 'Clinical Credentials',
    'registration.form.main_specialty': 'Main Specialty',
    'registration.form.select_specialty': 'Select a specialty...',
    'registration.form.professional_license': 'Professional License',
    'registration.form.years_experience': 'Years of Experience',
    'registration.form.validation_title': 'Credential Validation',
    'registration.form.upload_license': 'Upload Professional License',
    'registration.form.drag_file': 'Drag your file here',
    'registration.form.file_format': 'PDF, JPG, PNG (Max 5MB)',
    'registration.form.upload_btn': 'Upload file',
    'registration.form.pending_upload': 'Pending upload',
    'registration.form.medical_degree': 'Medical Degree',
    'registration.form.drag_degree': 'Drag your degree here',
    'registration.form.legalized_copy': 'Legalized copy (Max 10MB)',
    'registration.form.capabilities': 'Capabilities',
    'registration.form.offered_specialties': 'Offered Specialties',
    'registration.form.contact': 'Contact',
    'registration.form.emergency_phone': 'Emergency Phone (24h)',
    'registration.form.medical_director': 'Responsible Medical Director',
    'registration.form.available_services': 'Available Services',
    'registration.form.attention_hours': 'Attention Hours',
    'registration.form.opening': 'Opening',
    'registration.form.closing': 'Closing',
    'registration.form.open_24h_active': '24 Hour Attention (Active Guard)',
    'registration.form.location': 'Location',
    'registration.form.detect_location': 'Detect Location',
    'registration.form.address_doctor': 'Physical Address / Clinic',
    'registration.form.address_clinic': 'Institutional Address',
    'registration.form.address_full': 'Full Address',
    'registration.form.address_doctor_ph': 'E.g. Main Ave 123, Office 4B',
    'registration.form.address_full_ph': 'Street, Number, Floor, City',
    'registration.form.latitude': 'Latitude',
    'registration.form.longitude': 'Longitude',
    'registration.form.finish_doctor': 'Finish Registration',
    'registration.form.finish_clinic': 'Register Institution',
    'registration.form.finish_establishment': 'Register Entity',
    'registration.form.cancel': 'Cancel',
    'registration.form.encrypted_info': 'Encrypted Information',
    'settings.title': 'Settings & Customization',
    'settings.subtitle': 'Manage how you interact with the platform and its appearance.',
    'settings.language': 'Language',
    'settings.appearance': 'Appearance',
    'settings.theme.light': 'Light Mode',
    'settings.theme.dark': 'Dark Mode',
    'settings.theme.desc.light': 'Light background, high contrast',
    'settings.theme.desc.dark': 'Deep tones, battery saving', //
    'appointments.access_reserved': 'Reserved Access',
    'appointments.login_prompt': 'To manage your appointments and view your medical history, please sign in securely.',
    'appointments.sync_data': 'Sync Data',
    'appointments.title': 'Appointment Management',
    'appointments.desc': 'Manage your upcoming consultations and review your AI-synchronized medical history.',
    'appointments.new_appointment': 'New Appointment',
    'appointments.search_ph': 'Search by doctor, specialty or location...',
    'appointments.filter.all': 'All',
    'appointments.filter.doctors': 'Doctors',
    'appointments.filter.labs': 'Laboratories',
    'appointments.filter.clinics': 'Clinics',
    'appointments.upcoming': 'Upcoming Appointments',
    'appointments.scheduled': 'Scheduled',
    'appointments.syncing': 'Syncing Schedule...',
    'appointments.default_medical': 'Medical Appointment',
    'appointments.default_location': 'Central Hospital, North Wing',
    'appointments.pending': 'Pending',
    'appointments.add_calendar': 'Add to calendar',
    'appointments.cancel_appt': 'Cancel appointment',
    'appointments.empty_title': 'Empty Schedule',
    'appointments.empty_desc': 'You have no scheduled appointments at this time. Start a request to schedule your next care.',
    'appointments.schedule_new': 'Schedule New Appointment',
    'appointments.recent_history': 'Recent History',
    'appointments.view_all_history': 'View all history',
    'appointments.no_symptoms': 'No symptoms',
    'appointments.date_unavailable': 'Date unavailable',
    'appointments.emergency': 'EMERGENCY',
    'appointments.completed': 'COMPLETED',
    'appointments.no_history': 'No recent history records.',
    'appointments.view_passport': 'View Full Health Passport',
    'appointments.general_doctor': 'General Doctor',
    'appointments.laboratory': 'Laboratory',
    'appointments.need_help': 'Need help?',
    'appointments.help_desc': 'If you have trouble finding an appointment or require technical assistance, contact our patient care team.',
    'appointments.contact_support': 'Contact Support',
    'appointments.confirm_cancel': 'Confirm Cancellation',
    'appointments.cancel_warning': 'Are you sure you want to cancel this appointment? This action cannot be undone.',
    'appointments.keep_appt': 'Keep Appointment',
    'appointments.yes_cancel': 'Yes, Cancel',
    'appointment.modal.imported_from_ai': 'Imported from AI Triage:\nSymptoms: {symptoms}\nRecommendation: {recommendation}',
    'appointment.modal.doctor_name': 'Dr. S. Ramirez',
    'appointment.modal.lab_name': 'Central Laboratory',
    'appointment.modal.hospital_name': 'Central Hospital, North Wing',
    'appointment.modal.title': 'New Appointment',
    'appointment.modal.subtitle': 'Complete the details to schedule your consultation.',
    'appointment.modal.service_type_label': 'SERVICE TYPE',
    'appointment.modal.medical_consultation': 'Medical Consultation',
    'appointment.modal.lab_analysis': 'Lab Analysis',
    'appointment.modal.specialty': 'Specialty',
    'appointment.modal.location_professional_label': 'LOCATION / PROFESSIONAL',
    'appointment.modal.search_placeholder': 'Search by name, specialty or center...',
    'appointment.modal.nearest': 'Nearest',
    'appointment.modal.date_time_label': 'DATE AND TIME',
    'appointment.modal.november_2024': 'November 2024',
    'appointment.modal.days.mon': 'M',
    'appointment.modal.days.tue': 'T',
    'appointment.modal.days.wed': 'W',
    'appointment.modal.days.thu': 'T',
    'appointment.modal.days.fri': 'F',
    'appointment.modal.days.sat': 'S',
    'appointment.modal.days.sun': 'S',
    'appointment.modal.available_times_prefix': 'Available Times - Nov ',
    'appointment.modal.available_times_suffix': '',
    'appointment.modal.notes_label': 'NOTES OR PREVIOUS SYMPTOMS',
    'appointment.modal.import_triage': 'Import from AI Triage',
    'appointment.modal.notes_placeholder': 'Briefly describe the reason for your consultation or symptoms...',
    'appointment.modal.cancel': 'Cancel',
    'appointment.modal.scheduling': 'Scheduling...',
    'appointment.modal.confirm': 'Confirm Appointment',
    'chat.simulation.search': 'Search or start a chat',
    'chat.simulation.name': 'Salud Conecta AI',
    'chat.simulation.subject': 'Medical Appointment Confirmation...',
    'chat.simulation.official': 'Official business',
    'chat.simulation.today': 'Today',
    'chat.simulation.security_msg': 'Calls and messages to this business are now end-to-end encrypted. Tap for more info.',
    'chat.simulation.message_title': 'Medical Appointment Confirmation',
    'chat.simulation.message_body': 'Hello. We are contacting you from <strong>Salud Conecta AI</strong> to confirm your next medical appointment.',
    'chat.simulation.specialist': 'Specialist',
    'chat.simulation.dr_name': 'Dr. Carlos Mendoza',
    'chat.simulation.dr_specialty': 'Cardiology',
    'chat.simulation.datetime': 'Date and Time',
    'chat.simulation.date': 'Friday, November 15',
    'chat.simulation.time': '09:00 AM',
    'chat.simulation.location_label': 'Location',
    'chat.simulation.location': 'Central Hospital, Tower B, Office 402.',
    'chat.simulation.open_maps': 'Open in Google Maps',
    'chat.simulation.important_instructions': 'Important instructions',
    'chat.simulation.instruction1': 'Arrive with an <strong>8-hour fast</strong>.',
    'chat.simulation.instruction2': 'Bring relevant <strong>previous studies</strong>.',
    'chat.simulation.instruction3': 'Arrive 15 minutes early.',
    'chat.simulation.confirm_prompt': 'Please confirm your attendance using the button below.',
    'chat.simulation.btn_confirm': 'Confirm attendance',
    'chat.simulation.btn_cancel': 'Cancel or reschedule',
    'chat.simulation.user_reply': 'Perfect, I will be there. Thank you very much for the reminder.',
    'chat.simulation.input_placeholder': 'Type a message',
    'chat.assistant.greeting': 'Hello. I am your Salud Conecta AI assistant. How can I help you today?',
    'chat.assistant.title': 'Salud Conecta AI Assistant',
    'chat.assistant.subtitle': 'Empathetic and Efficient • Available 24/7',
    'chat.assistant.role_ai': 'AI Assistant',
    'chat.assistant.role_user': 'You',
    'chat.assistant.thinking': 'Thinking...',
    'chat.assistant.input_placeholder': 'Type your query here...',
    'chat.assistant.disclaimer': 'AI can make mistakes. Verify important information.',
    'settings.notifications': 'Notifications',
    'settings.notif.critical': 'Medical Alerts (Critical)',
    'settings.notif.critical.desc': 'Unavoidable medication reminders and urgent appointment confirmations.',
    'settings.notif.challenges': 'Health Challenges',
    'settings.notif.challenges.desc': 'Daily motivation, step reminders, hydration and sleep tracking.',
    'settings.notif.benefits': 'Premium Benefits',
    'settings.notif.benefits.desc': 'Alerts for coupons about to expire, new discounts and rewards.',
    'settings.channels': 'Delivery Channels',
    'settings.channels.push': 'Push (App)',
    'settings.channels.whatsapp': 'WhatsApp',
    'settings.channels.email': 'Email',
    'settings.summary': 'Daily Summary', //
    'settings.summary.desc': 'Group challenge and benefit notifications into a single daily delivery to reduce distractions.',
    'settings.summary.time': 'Delivery time',
    'settings.save': 'Save Changes',
    'settings.saving': 'Saving...',
    'settings.processed': 'Changes Synchronized!',
    'settings.processing': 'Processing...',
    'settings.config.alerts': 'Alert Configuration',
    'settings.config.desc': 'Your changes are automatically saved in your secure vault.', //
    'settings.theme.light.label': 'Light background, high contrast',
    'settings.theme.dark.label': 'Deep tones, battery saving',
    'settings.channels.push.label': 'Push (App)',
    'settings.channels.whatsapp.label': 'WhatsApp',
    'settings.channels.email.label': 'Email',
    'settings.summary.label': 'Group challenge and benefit notifications into a single daily delivery to reduce distractions.',
    'settings.notif.critical.label': 'Recommended to keep active',
    'wallet.title': 'Health Points', //
    'wallet.balance': 'Current Balance',
    'wallet.history': 'Recent History',
    'wallet.rewards': 'Premium Rewards',
    'hero.badge': 'INTEGRAL PUBLIC HEALTH SYSTEM',
    'hero.title': 'Empathetic {efficiency} at your health\'s service.',
    'hero.subtitle': 'We transform uncertainty into verified action routes. AI Triage, stock maps, and digital health passport.',
    'hero.cta.primary': 'Start AI Triage',
    'hero.cta.secondary': 'Realon™ Protocol',
    'features.title': 'Comprehensive Services',
    'features.1.title': 'Institutional Reliability', //
    'features.1.desc': 'Information verified directly from official public health sources.',
    'features.2.title': 'Empathetic Efficiency',
    'features.2.desc': 'Designed to reduce your mental load in times of need.',
    'features.3.title': 'Universal Access',
    'features.3.desc': 'Interface optimized for maximum readability and ease of use.',
    'status.network': 'HEALTH NETWORK',
    'status.active': 'ACTIVE',
    'status.pharmacies': '24H PHARMACIES',
    'status.available': 'AVAILABLE',
    'status.emergency': 'EMERGENCIES',
    'status.call': 'CALL',
    'cta.professional.title': 'Are you a healthcare professional or pharmacy manager?', //
    'cta.professional.desc': 'Join the interoperable {brand} network. Register your lab, clinic or pharmacy to appear on the real-time stock and availability map.',
    'cta.professional.doctor': 'I am Professional',
    'cta.professional.clinic': 'Health Center',
    'cta.professional.business': 'Lab/Pharmacy',
    'footer.desc': 'Intelligent public health ecosystem developed to maximize efficiency and empathy in national healthcare.',
    'footer.system': 'System',
    'footer.system.triage': 'Advanced Triage',
    'footer.system.pharmacy': 'Pharmacy Network',
    'footer.system.pwa': 'PWA Passport',
    'footer.legal': 'Legal', //
    'footer.legal.privacy': 'Privacy',
    'footer.legal.terms': 'Terms',
    'footer.legal.acc': 'Accessibility',
    'footer.emergency.desc': 'If you feel your life is in danger or have critical symptoms, do not use this tool and call 128 (Red Cross) or 115 immediately.',
    'pharmacy.badge': 'Premium Member',
    'pharmacy.title': 'Pharmacy Discounts & Benefits',
    'pharmacy.subtitle': 'Exclusive access to preferential prices on chronic and over-the-counter medications in our network of verified pharmacies.',
    'pharmacy.search_placeholder': 'Search medications to see premium prices...',
    'pharmacy.scan_prescription': 'Scan Prescription',
    'pharmacy.my_coupons': 'My Active Coupons', //
    'pharmacy.verified_title': 'Verified Premium Pharmacies',
    'pharmacy.view_all': 'View all',
    'pharmacy.qr_code': 'Show QR',
    'pharmacy.expires_in': 'Expires in',
    'pharmacy.card_chronic': 'Chronic Treatment',
    'pharmacy.card_general': 'General Pharmacy',
    'pharmacy.card_chronic_desc': 'Valid for cardiovascular and metabolic medication.',
    'pharmacy.card_general_desc': 'Applies to over-the-counter and personal care products.',
    'activity.title': 'Activity Logs',
    'activity.subtitle': 'Your health progress and challenges completed this week.', //
    'activity.week': 'Week',
    'activity.month': 'Month',
    'activity.daily_progress': 'Daily Progress',
    'activity.active_challenges': 'Active Challenges',
    'activity.recent': 'Recent Activity',
    'activity.view_all': 'View full history',
    'activity.days': 'days',
    'activity.morning_walk': 'Morning walk',
    'activity.today': 'Today',
    'activity.hydration_session': 'Hydration session',
    'activity.yesterday': 'Yesterday', //
    'activity.blood_pressure': 'Blood Pressure Log',
    'activity.monthly_goal_reached_water': 'Monthly goal reached (Water)',
    'activity.monthly_checkup': 'Monthly Medical Checkup',
    'activity.5_days_ago': '5 days ago',
    'activity.reward': 'Rewards',
    'activity.current_progress': 'Current Progress',
    'activity.goal': 'Goal',
    'activity.progress': 'Progress',
    'activity.completed_yesterday': 'Completed yesterday',
    'activity.3_days_ago': '3 days ago',
    'stats.total_steps': 'Total Steps', //
    'stats.vs_prev_week': 'vs prev week',
    'stats.vs_prev_month': 'vs prev month',
    'stats.active_calories': 'Active Calories',
    'stats.estimated': 'estimated',
    'stats.activity_min': 'Activity Min.',
    'stats.goal_reached': 'Goal reached',
    'stats.stable_avg': 'Stable average',
    'stats.activity': 'activity',
    'challenges.title': 'Health Challenges', //
    'challenges.subtitle': 'Complete healthy habits to earn extra points and improve your general well-being.',
    'challenges.weekly': 'Weekly',
    'challenges.monthly': 'Monthly',
    'challenges.available': 'Available Challenges',
    'challenges.join': 'Join Challenge',
    'challenges.ranking': 'Global Ranking',
    'challenges.level': 'Level',
    'challenges.next_level': 'Next Level',
    'challenges.sync': 'Sync',
    'challenges.perfect_week': 'Perfect Week', //
    'challenges.streak': '5 Day Streak',
    'challenges.hero_hydration': 'Hydration Hero',
    'challenges.hero_hydration_desc': 'Log 2 liters of water daily for 5 consecutive days.',
    'challenges.restful_sleep': 'Restful Sleep',
    'challenges.restful_sleep_desc': 'Sleep at least 7 hours each night for the entire week.',
    'challenges.active_weekend': 'Active Weekend',
    'challenges.active_weekend_desc': 'Perform 60 minutes of outdoor physical activity this weekend.',
    'challenges.marathon': 'Monthly Marathon',
    'challenges.marathon_desc': 'Complete 300,000 steps during the month.',
    'challenges.sleep_consistency': 'Sleep Consistency', //
    'challenges.sleep_consistency_desc': 'Maintain a regular sleep schedule for 4 weeks in a row.',
    'challenges.mindfulness': 'Mindfulness 30',
    'challenges.mindfulness_desc': 'Perform 30 meditation sessions this month.',
    'challenges.steps_10k': '10k Daily Steps',
    'challenges.steps_10k_desc': 'Maintain an average of 10,000 steps throughout the week.',
    'challenges.day_4_of_7': 'Day 4 of 7 consecutive',
    'challenges.optimal_hydration': 'Optimal Hydration',
    'challenges.drink_2l_daily_week': 'Drink 2L daily (Week)', //
    'challenges.your_profile': 'Your Profile',
    'challenges.current_challenge': 'Current Challenge',
    'challenges.coming_soon': 'Next challenges in 3 days',
    'challenges.achievements': 'Recent Achievements',
    'challenges.you': 'YOU',
    'challenges.left_pts': '850 pts left',
    'maps.premium.filter_all': 'All',
    'maps.premium.filter_hospitals': 'Hospitals',
    'maps.premium.filter_clinics': 'Clinics',
    'maps.premium.filter_labs': 'Labs',
    'maps.premium.filter_pharmacies': 'Pharmacies',
    'maps.premium.type_hospital': 'Private Hospital',
    'maps.premium.type_clinic': 'Private Clinic',
    'maps.premium.type_lab': 'Laboratory',
    'maps.premium.type_pharmacy': 'Premium Pharmacy',
    'maps.premium.type_dental': 'Dental Clinic',
    'maps.premium.type_private': 'Private Service',
    'maps.premium.req_title': 'Premium Access Required',
    'maps.premium.req_subtitle': "Unlock Nicaragua's Private Health Network",
    'maps.premium.feat_1': 'Exclusive private clinics and hospitals',
    'maps.premium.feat_2': 'Skip lines with AI-prioritized scheduling',
    'maps.premium.feat_3': 'Top-rated doctors and specialists',
    'maps.premium.feat_4': 'Premium discounts at labs and pharmacies',
    'maps.premium.get_now': 'Get Premium Now',
    'maps.premium.hero_title': 'Premium Health Network',
    'maps.premium.hero_subtitle': 'Private centers and top-tier specialists',
    'maps.premium.exclusive_service': 'Exclusive Service',
    'search.hero_title': 'Find quality medical care',
    'search.hero_subtitle': 'Search for hospitals, clinics, pharmacies and labs near you',
    'maps.premium.stat_vip': 'VIP Centers',
    'maps.premium.stat_near': 'Nearby (<5km)',
    'maps.premium.stat_rating': 'Top Rated',
    'maps.premium.search_placeholder': 'Search private clinics, hospitals, or pharmacies...',
    'maps.premium.no_results': 'No facilities found',
    'maps.premium.no_results_desc': 'Try adjusting your filters or searching for other terms.',
    'maps.premium.24h': '24 Hours',
    'maps.premium.view_profile': 'View Profile',
    'maps.premium.directions': 'Directions',
    'maps.premium.prev': 'Previous',
    'maps.premium.page': 'Page',
    'maps.premium.of': 'of',
    'maps.premium.next': 'Next',
    'maps.premium.red_premium': 'Premium Network',
    'maps.premium.authorized_center': 'Authorized Premium Center',
    'maps.premium.about_center': 'About the Center',
    'maps.premium.about_desc': 'Premier private medical institution with modern equipment and personalized care.',
    'maps.premium.services': 'Specialties & Services',
    'maps.premium.direct_phone': 'Direct Contact Phone',
    'maps.premium.location_coords': 'Location',
    'maps.premium.open_maps': 'Open in Maps',
    'maps.premium.schedule_turn': 'Schedule Appointment'
  }
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    return (localStorage.getItem('language') as Language) || 'es';
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('language', lang);
  };

  const t = (key: string) => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
